apiVersion: v1
kind: ConfigMap
metadata:
  name: ecomm-config
data:
  # Database Names
  PRODUCTS_DB_NAME: products
  ORDERS_DB_NAME: orders
  CUSTOMERS_DB_NAME: customers

  # Storage Config (non-sensitive values only)
  AZURE_STORAGE_CONTAINER_NAME: product-images
  AZURE_SAS_TOKEN_EXPIRY_HOURS: "24"

  # Internal service URLs (cluster DNS within Kubernetes)
  PRODUCT_SERVICE_URL: http://product-service:8000
  ORDER_SERVICE_URL: http://order-service:8000
  CUSTOMER_SERVICE_URL: http://customer-service:8000
