name: CI - Test, Build & Push (testing)
 
on:
  workflow_dispatch:
  push:
    branches: [ testing ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'

# Cancel older runs on the same branch to avoid overlapping builds
concurrency:
  group: ci-testing-${{ github.ref }}
  cancel-in-progress: true

env:
  # e.g., s224005289week10acr.azurecr.io  (GitHub Secret)
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  # Full JSON for azure/login (GitHub Secret)
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  # Use testing prefix like you had
  TAG: testing-${{ github.sha }}

jobs:
  # --- Run backend tests against service Postgres containers ---
  test_backends:
    runs-on: ubuntu-latest

    services:
      # Product DB
      product_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: products
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      # Order DB
      order_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orders
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

      # Customer DB
      customer_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: customers
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5434:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Reuse week08: Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- customer_service ---
      - name: Install test deps (customer_service)
        working-directory: backend/customer_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests (customer_service)
        working-directory: backend/customer_service
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5434
          POSTGRES_DB: customers
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5434/customers
        run: pytest --maxfail=1 --disable-warnings -q

      # --- product_service ---
      - name: Install test deps (product_service)
        working-directory: backend/product_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests (product_service)
        working-directory: backend/product_service
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: products
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/products
        run: pytest --maxfail=1 --disable-warnings -q

      # --- order_service ---
      - name: Install test deps (order_service)
        working-directory: backend/order_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests (order_service)
        working-directory: backend/order_service
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          POSTGRES_DB: orders
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5433/orders
        run: pytest --maxfail=1 --disable-warnings -q

  # --- Build & Push images (only if tests pass) ---
  build_and_push_images:
    runs-on: ubuntu-latest
    needs: test_backends

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure login using a Service Principal secret
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Needs to be set as a GitHub Secret (Service Principal JSON)

      # Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_LOGIN_SERVER }}

      # Install Docker Scout (week08 reuse)
      - name: Install latest Docker Scout
        run: curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh


      # --- Build and Push: customer_service ---
      - name: Build customer_service
        run: |
          docker build \
            -t ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.TAG }} \
            -f backend/customer_service/Dockerfile backend/customer_service
      - name: Push customer_service
        run: docker push ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.TAG }}

      # --- Build and Push: product_service ---
      - name: Build product_service
        run: |
          docker build \
            -t ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.TAG }} \
            -f backend/product_service/Dockerfile backend/product_service
      - name: Push product_service
        run: docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.TAG }}

      # --- Build and Push: order_service ---
      - name: Build order_service
        run: |
          docker build \
            -t ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.TAG }} \
            -f backend/order_service/Dockerfile backend/order_service
      - name: Push order_service
        run: docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.TAG }}

      # --- Build and Push: frontend ---
      - name: Build frontend
        run: |
          docker build \
            -t ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.TAG }} \
            -f frontend/Dockerfile frontend
      - name: Push frontend
        run: docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.TAG }}

      - name: Azure Logout
        if: always()
        run: az logout
