name: CI - Test, Build & Push (testing)
 
on:
  workflow_dispatch:
  push:
    branches: [ testing ]

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  TAG: testing-${{ github.sha }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest


    services:
      # Product DB container
      product_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: products
        # Make pg_isready available so the service is healthy before tests run
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      # Order DB
      order_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orders
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      # Customer DB
      customer_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: customers
        ports:
          - 5434:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

          
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- customer_service ---
      - name: Install test deps (customer_service)
        working-directory: backend/customer_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests (customer_service)
        working-directory: backend/customer_service
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5434
          POSTGRES_DB: customers
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          # Belt-and-braces: some apps prefer DATABASE_URL; this overrides defaults.
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5434/customers
        run: pytest -q

      # --- product_service ---
      - name: Install test deps (product_service)
        working-directory: backend/product_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests (product_service)
        working-directory: backend/product_service
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: products
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/products
        run: pytest -q

      # --- order_service ---
      - name: Install test deps (order_service)
        working-directory: backend/order_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests (order_service)
        working-directory: backend/order_service
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          POSTGRES_DB: orders
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5433/orders
        run: pytest -q

      # ---- Push images to ACR only after tests pass ----
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Derive ACR name & login
        shell: bash
        run: |
          ACR_NAME="${{ env.ACR_LOGIN_SERVER }}"
          # If a login server was provided, strip the suffix to get the registry name
          ACR_NAME="${ACR_NAME%%.azurecr.io}"
          echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV
          az acr login --name "$ACR_NAME"

      - name: Build & Push customer_service
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.TAG }} -f backend/customer_service/Dockerfile backend/customer_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.TAG }}

      - name: Build & Push product_service
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.TAG }} -f backend/product_service/Dockerfile backend/product_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.TAG }}

      - name: Build & Push order_service
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.TAG }} -f backend/order_service/Dockerfile backend/order_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.TAG }}

      - name: Build & Push frontend
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.TAG }} -f frontend/Dockerfile frontend
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.TAG }}

      - name: Azure Logout
        if: always()
        run: az logout
